name: CustomItems
version: 1.2.0
main: ru.osk.customitems.CustomItems
api-version: 1.16
authors: [ osk ]
commands:
  customitems:
    usage: "customitems [give|list] [id] [player] (amount)"
    aliases: [ ci ]